/*
 * Copyright (C) 2026 Windham Windup
 *
 * This file was automatically generated by SmartDashboardCommandProcessor.
 * Do not modify this file manually - it will be regenerated on each build.
 * 
 * NOTE: This example file is provided in src/ for reference during development.
 * In production, this file is auto-generated in build/generated/sources/annotationProcessor/
 */
package frc.robot;

import edu.wpi.first.wpilibj.smartdashboard.SmartDashboard;

/**
 * Auto-generated class for registering @SmartDashboardCommand annotated methods.
 * <p>Generated at compile time by SmartDashboardCommandProcessor.
 */
public final class SmartDashboardCommands {

    private SmartDashboardCommands() {
        throw new UnsupportedOperationException("This is a utility class and cannot be instantiated");
    }

    /**
     * Registers all commands annotated with @SmartDashboardCommand on the SmartDashboard.
     * <p>This method should be called from RobotContainer after all subsystems are initialized.
     * @param container The RobotContainer instance containing all subsystems
     */
    public static void register(RobotContainer container) {
        // Commands from frc.robot.subsystems.intake.IntakeSuperstructure
        SmartDashboard.putData("Intake Linear/Extend", container.intake.extendLinear());
        SmartDashboard.putData("Intake Linear/Extend Intake", container.intake.extendIntake());
        SmartDashboard.putData("Intake Linear/Retract", container.intake.retractIntake());
        SmartDashboard.putData("Intake Linear/Cycle", container.intake.cycle());
        SmartDashboard.putData("Intake Linear/Coast", container.intake.linearCoast());

    }
}
