name: Build

on:
  push:

jobs:
  run_tests:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: "temurin"
          java-version: "17"
      - name: Cache Gradle dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: gradle-${{ runner.os }}-${{ hashFiles('**/*.gradle', '**/gradle-wrapper.properties', 'vendordeps/**') }}
          restore-keys: |
            gradle-${{ runner.os }}-
      - name: Grant execute permission
        run: chmod +x gradlew
      - name: Build Robot Code
        run: ./gradlew build -x test
      - name: Test Robot Code
        run: ./gradlew test
      - name: Check Formatting
        run: ./gradlew spotlessCheck